const STORAGE='omSaiCatalogV1';
const ORDERS='omSaiOrdersV1';
const ADMIN='omSaiAdminV1';
const WA='+9779845191093';
const defaultData={categoryImages:{},delivery:{cementThreshold:20,cementCharge:25,tmtBundleThreshold:4,tmtCharge:150,otherBillThreshold:5000,otherCharge:100},categories:['Cement','TMT','Binding Wire','Paints','Plumbing','Equipment','Nails','Others'],products:[
{id:'cem-jagdamba',category:'Cement',name:'PPC Cement',brand:'Jagdamba',unit:'Bag',price:500,image:'cement.svg'},
{id:'cem-vishwa',category:'Cement',name:'PPC Cement',brand:'Vishwakarma',unit:'Bag',price:500,image:'cement.svg'},
{id:'cem-ultra',category:'Cement',name:'OPC Cement',brand:'Ultra',unit:'Bag',price:600,image:'cement.svg'},
{id:'tmt-8',category:'TMT',name:'8 mm TMT',brand:'Jagdamba',unit:'Kg',price:103.5,kgPiece:5,kgBundle:100,image:'tmt.svg'},
{id:'tmt-10',category:'TMT',name:'10 mm TMT',brand:'Jagdamba',unit:'Kg',price:100,kgPiece:7.5,kgBundle:110,image:'tmt.svg'},
{id:'tmt-12',category:'TMT',name:'12 mm TMT',brand:'Jagdamba',unit:'Kg',price:100,kgPiece:11,kgBundle:110,image:'tmt.svg'},
{id:'tmt-16',category:'TMT',name:'16 mm TMT',brand:'Jagdamba',unit:'Kg',price:100,kgPiece:20,kgBundle:100,image:'tmt.svg'},
{id:'torkari-7',category:'TMT',name:'7 mm Torkari',brand:'Jagdamba',unit:'Kg',price:110,kgPiece:1.5,kgBundle:60,image:'tmt.svg'},
{id:'torkari-475',category:'TMT',name:'4.75 mm Torkari',brand:'Jagdamba',unit:'Kg',price:112,kgPiece:1,kgBundle:1,image:'tmt.svg'},
{id:'putty-jk',category:'Paints',name:'Wall Putty',brand:'JK',unit:'Bag',price:1250,image:'putty.svg'},
{id:'putty-asian',category:'Paints',name:'Wall Putty',brand:'Asian Paints',unit:'Bag',price:1350,image:'putty.svg'},
{id:'putty-birla',category:'Paints',name:'Wall Putty',brand:'Birla',unit:'Bag',price:1250,image:'putty.svg'},
{id:'putty-ashoka',category:'Paints',name:'Wall Putty',brand:'Ashoka',unit:'Bag',price:1250,image:'putty.svg'},
{id:'primer-ai',category:'Paints',name:'Interior Primer',brand:'Asian Paints',unit:'Litre',packs:{1:300,4:1100,10:2200,20:4100},image:'paint.svg'},
{id:'primer-ah',category:'Paints',name:'Interior Primer',brand:'Ashoka',unit:'Litre',packs:{1:200,4:750,10:1600,20:3200},image:'paint.svg'},
{id:'primer-ae',category:'Paints',name:'Exterior Primer',brand:'Asian Paints',unit:'Litre',packs:{1:500,4:2000,10:4000,20:6200},image:'paint.svg'},
{id:'primer-eh',category:'Paints',name:'Exterior Primer',brand:'Ashoka',unit:'Litre',packs:{1:400,4:1600,10:2100,20:4200},image:'paint.svg'},
{id:'tractor',category:'Paints',name:'Tractor Interior Emulsion',brand:'Asian Paints',unit:'Litre',packs:{1:500,4:1800,10:3700,20:6200},image:'paint.svg'},
{id:'premium-a',category:'Paints',name:'Premium Emulsion',brand:'Asian Paints',unit:'Litre',packs:{1:700,4:2800,10:7000,20:14000},image:'paint.svg'},
{id:'royale',category:'Paints',name:'Royale Emulsion',brand:'Asian Paints',unit:'Litre',packs:{1:1000,4:4000,10:10000,20:20000},image:'paint.svg'},
{id:'shyne',category:'Paints',name:'Royale Shyne',brand:'Asian Paints',unit:'Litre',packs:{1:1200,4:4800,10:12000,20:24000},image:'paint.svg'},
{id:'aspira',category:'Paints',name:'Royale Aspira',brand:'Asian Paints',unit:'Litre',packs:{1:1400,4:5600,10:14000,20:28000},image:'paint.svg'},
{id:'interior-ashoka',category:'Paints',name:'Interior Emulsion',brand:'Ashoka',unit:'Litre',packs:{1:250,4:1000,10:2500,20:5000},image:'paint.svg'},
{id:'premium-ashoka',category:'Paints',name:'Premium Emulsion',brand:'Ashoka',unit:'Litre',packs:{1:500,4:2000,10:5000,20:10000},image:'paint.svg'},
{id:'ace',category:'Paints',name:'ACE Emulsion',brand:'Asian Paints',unit:'Litre',packs:{1:350,4:1400,10:3500,20:7000},image:'paint.svg'},
{id:'apex',category:'Paints',name:'APEX Emulsion',brand:'Asian Paints',unit:'Litre',packs:{1:700,4:2800,10:7000,20:14000},image:'paint.svg'},
{id:'apex-ultima',category:'Paints',name:'APEX ULTIMA Emulsion',brand:'Asian Paints',unit:'Litre',packs:{1:1000,4:4000,10:10000,20:20000},image:'paint.svg'},
{id:'ultima-protek',category:'Paints',name:'ULTIMA Protek Shyne',brand:'Asian Paints',unit:'Litre',packs:{1:1200,4:4800,10:12000,20:24000},image:'paint.svg'},
{id:'tee',category:'Plumbing',name:'Tee',brand:'Aquatech',unit:'Piece',variants:{'2.5 inch':200,'4 inch':250},image:'plumbing.svg'},
{id:'nail-1',category:'Nails',name:'1 inch Nail',brand:'Jagdamba',unit:'Kg',price:150,image:'nails.svg'},
{id:'nail-15',category:'Nails',name:'1.5 inch Nail',brand:'Jagdamba',unit:'Kg',price:150,image:'nails.svg'},
{id:'nail-2',category:'Nails',name:'2 inch Nail',brand:'Jagdamba',unit:'Kg',price:150,image:'nails.svg'},
{id:'nail-25',category:'Nails',name:'2.5 inch Nail',brand:'Jagdamba',unit:'Kg',price:150,image:'nails.svg'},
{id:'nail-3',category:'Nails',name:'3 inch Nail',brand:'Jagdamba',unit:'Kg',price:150,image:'nails.svg'},
{id:'nail-4',category:'Nails',name:'4 inch Nail',brand:'Jagdamba',unit:'Kg',price:150,image:'nails.svg'},
{id:'wire-22',category:'Binding Wire',name:'22 Gauge Binding Wire',brand:'Jagdamba',unit:'Kg',price:150,image:'wire.svg'},
{id:'wire-20',category:'Binding Wire',name:'20 Gauge Binding Wire',brand:'Jagdamba',unit:'Kg',price:150,image:'wire.svg'},
{id:'shovel',category:'Equipment',name:'Shovel',brand:'Pashupati',unit:'Piece',price:350,image:'equipment.svg'},
{id:'kufal',category:'Equipment',name:'Kufal',brand:'Pashupati',unit:'Piece',price:500,image:'equipment.svg'},
{id:'kathara',category:'Equipment',name:'Kathara',brand:'Pashupati',unit:'Piece',price:300,image:'equipment.svg'},
{id:'hammer',category:'Equipment',name:'Hammer',brand:'Pashupati',unit:'Piece',price:500,image:'equipment.svg'},
{id:'kabja',category:'Others',name:'Kabja',brand:'',unit:'Kg',price:150,image:'others.svg'}]};
let data=loadData(),cart=JSON.parse(localStorage.getItem('omSaiCartV1')||'[]'),activeCategory='All',visibleProductCount=12,selectedFulfillment='delivery';
function loadData(){try{const saved=JSON.parse(localStorage.getItem(STORAGE)); if(saved){saved.categoryImages=saved.categoryImages||{}; return saved} return structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function saveData(){localStorage.setItem(STORAGE,JSON.stringify(data));renderAll()}
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}
function img(p){return p.imageData||('assets/'+(p.image||'cement.svg'))}
function categoryImg(c){return data.categoryImages?.[c]||'assets/'+({Cement:'cement.svg',TMT:'tmt.svg','Binding Wire':'wire.svg',Paints:'paint.svg',Plumbing:'plumbing.svg',Equipment:'equipment.svg',Nails:'nails.svg',Others:'others.svg'}[c]||'others.svg')}
function readImage(file,cb){if(!file)return cb('');if(file.size>2*1024*1024){toast('Image must be 2MB or smaller');return cb('')}const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
const icons={Cement:'▰',TMT:'╱', 'Binding Wire':'⌁',Paints:'◉',Plumbing:'⌁',Equipment:'⚒',Nails:'•',Others:'＋'};
function renderCategories(){document.getElementById('categoryGrid').innerHTML=data.categories.map(c=>`<button class="category-card" onclick="setCategory('${c}')"><span class="cat-icon" style="overflow:hidden"><img src="${categoryImg(c)}" alt="" style="width:100%;height:100%;object-fit:cover"></span><strong>${c}</strong><span>${data.products.filter(p=>p.category===c).length} products</span></button>`).join('')}
function renderFilters(){document.getElementById('filterRow').innerHTML=['All',...data.categories].map(c=>`<button class="filter-btn ${activeCategory===c?'active':''}" onclick="setCategory('${c}')">${c}</button>`).join('')}
function displayPrice(p){if(p.packs)return 'From '+money(Math.min(...Object.values(p.packs)))+'/L';if(p.variants)return 'From '+money(Math.min(...Object.values(p.variants)))+'/piece';return money(p.price)+'/'+p.unit}
function renderProducts(){const source=activeCategory==='All'?data.products:data.products.filter(p=>p.category===activeCategory);const list=source.slice(0,visibleProductCount);document.getElementById('productHeading').textContent=activeCategory==='All'?'Popular materials':activeCategory;document.getElementById('productGrid').innerHTML=list.map(p=>`<article class="product-card"><div class="product-img"><img src="${img(p)}" alt="${p.name}"></div><div class="product-body"><small>${p.brand||'Om Sai International'}</small><h4>${p.name}</h4><div class="product-price">${displayPrice(p)}</div><div class="product-meta">${p.category==='TMT'?`${p.kgPiece} kg/piece · ${p.kgBundle} kg/bundle`:p.category==='Paints'&&p.packs?'1L · 4L · 10L · 20L':p.unit}</div><button class="add-btn" onclick="openProduct('${p.id}')">View & add</button></div></article>`).join('');const more=document.getElementById('moreProductsBtn');if(more){more.style.display=source.length>visibleProductCount?'inline-flex':'none';more.textContent=visibleProductCount<source.length?`More products (${source.length-visibleProductCount}) →`:'More products';}}
function renderAll(){renderCategories();renderFilters();renderProducts();updateCart()}
function setCategory(c){activeCategory=c;visibleProductCount=12;renderFilters();renderProducts();document.getElementById('product-list').scrollIntoView({behavior:'smooth',block:'start'})}
function openPopularMaterials(e){if(e)e.preventDefault();activeCategory='All';visibleProductCount=12;renderAll();document.getElementById('product-list').scrollIntoView({behavior:'smooth',block:'start'})}
function showMoreProducts(){visibleProductCount+=12;renderProducts()}
function openProduct(id){const p=data.products.find(x=>x.id===id);if(!p)return;let extra='';if(p.category==='TMT')extra=`<div class="option-grid"><label>Order mode<select id="tmtMode"><option value="bundle">Bundle</option><option value="piece">Piece</option><option value="both">Both</option></select></label><label>Bundle quantity<input id="tmtBundle" type="number" min="0" value="1"></label><label>Piece quantity<input id="tmtPiece" type="number" min="0" value="0"></label></div>`;else if(p.packs)extra=`<label>Pack size<select id="paintPack"><option value="1">1 Litre — ${money(p.packs[1])}</option><option value="4">4 Litre — ${money(p.packs[4])}</option><option value="10">10 Litre — ${money(p.packs[10])}</option><option value="20">20 Litre — ${money(p.packs[20])}</option></select></label><label>Quantity<input id="qty" type="number" min="1" value="1"></label><label>Colour Code<input id="colour" placeholder="e.g. 1234"></label><p class="hint">Colour charges will be decided by the dealer at the time of delivery. For details, please contact us.</p>`;else if(p.variants)extra=`<label>Size<select id="variant">${Object.entries(p.variants).map(([k,v])=>`<option value="${k}">${k} — ${money(v)}/piece</option>`).join('')}</select></label><label>Quantity<input id="qty" type="number" min="1" value="1"></label>`;else extra=`<label>Quantity<input id="qty" type="number" min="1" value="1"></label>`;document.getElementById('productModalBody').innerHTML=`<div style="display:grid;grid-template-columns:1fr 1fr;gap:24px;align-items:center"><div class="product-img" style="height:260px;border-radius:18px"><img src="${img(p)}" alt="${p.name}"></div><div><span class="eyebrow">${p.category}</span><h3 style="font:800 30px Manrope;margin:8px 0">${p.name}</h3><p style="color:#7b7485">${p.brand||''}</p>${extra}<button class="primary-btn full" onclick="addConfigured('${p.id}')">Add to cart</button></div></div>`;document.getElementById('productModal').classList.add('show');if(p.category==='TMT')toggleTmtInputs()}
function toggleTmtInputs(){const m=document.getElementById('tmtMode');if(!m)return;const b=document.getElementById('tmtBundle').parentElement,c=document.getElementById('tmtPiece').parentElement;const mode=m.value;b.style.display=mode==='piece'?'none':'';c.style.display=mode==='bundle'?'none':'';m.onchange=toggleTmtInputs}
function addConfigured(id){const p=data.products.find(x=>x.id===id);let item={id,qty:1};if(p.category==='TMT'){const mode=document.getElementById('tmtMode').value,b=+document.getElementById('tmtBundle').value||0,c=+document.getElementById('tmtPiece').value||0;if(mode==='bundle'&&b<1)return toast('Enter bundle quantity');if(mode==='piece'&&c<1)return toast('Enter piece quantity');if(mode==='both'&&(b<1&&c<1))return toast('Enter at least one quantity');item.mode=mode;item.bundles=mode==='piece'?0:b;item.pieces=mode==='bundle'?0:c}else{item.qty=+document.getElementById('qty')?.value||1;if(p.packs)item.pack=+document.getElementById('paintPack').value;if(p.variants)item.variant=document.getElementById('variant').value;if(document.getElementById('colour'))item.colour=document.getElementById('colour').value}cart.push(item);localStorage.setItem('omSaiCartV1',JSON.stringify(cart));closeModal('productModal');updateCart();showCartBar();toast('Added to cart — keep shopping') }
function itemCalc(item){const p=data.products.find(x=>x.id===item.id);if(p.category==='TMT'){const kg=(item.bundles||0)*p.kgBundle+(item.pieces||0)*p.kgPiece;return {subtotal:kg*p.price,weight:kg,desc:`${item.bundles||0} bundle · ${item.pieces||0} piece`}}if(p.packs){return {subtotal:p.packs[item.pack]*item.qty,desc:`${item.pack} L × ${item.qty}`}}if(p.variants){return {subtotal:p.variants[item.variant]*item.qty,desc:`${item.variant} × ${item.qty}`}}return {subtotal:p.price*item.qty,desc:`${item.qty} × ${p.unit}`}}
function totals(mode=selectedFulfillment){let subtotal=cart.reduce((s,i)=>s+itemCalc(i).subtotal,0),delivery=0;if(mode==='pickup')return {subtotal,delivery:0,total:subtotal};const hasC=cart.some(i=>data.products.find(p=>p.id===i.id)?.category==='Cement'),hasT=cart.some(i=>data.products.find(p=>p.id===i.id)?.category==='TMT'),otherOnly=cart.some(i=>{const c=data.products.find(p=>p.id===i.id)?.category;return c&&!['Cement','TMT'].includes(c)});if(hasC){const bags=cart.filter(i=>data.products.find(p=>p.id===i.id)?.category==='Cement').reduce((s,i)=>s+i.qty,0);if(bags<data.delivery.cementThreshold)delivery+=bags*data.delivery.cementCharge}if(hasT){const bundles=cart.filter(i=>data.products.find(p=>p.id===i.id)?.category==='TMT').reduce((s,i)=>s+(i.bundles||0),0);if(bundles<data.delivery.tmtBundleThreshold)delivery+=bundles*data.delivery.tmtCharge}if(otherOnly&&subtotal<data.delivery.otherBillThreshold)delivery+=data.delivery.otherCharge;return {subtotal,delivery,total:subtotal+delivery}}
function cartItemCount(i){if(i.bundles!==undefined||i.pieces!==undefined)return (i.bundles||0)+(i.pieces||0);return i.qty||0}
function updateCart(){document.getElementById('cartCount').textContent=cart.reduce((s,i)=>s+cartItemCount(i),0);const el=document.getElementById('cartItems');if(!cart.length){el.innerHTML='<div class="empty">Your cart is empty.<br>Choose materials to get started.</div>'}else el.innerHTML=cart.map((i,n)=>{const p=data.products.find(x=>x.id===i.id);if(p?.packs&&!i.pack)i.pack=1;const c=itemCalc(i);let controls='';if(p.category==='TMT'){const mode=i.mode||'bundle';controls=`<div class="cart-control-stack"><label>Order mode<select onchange="setTmtMode(${n},this.value)"><option value="bundle" ${mode==='bundle'?'selected':''}>Bundle</option><option value="piece" ${mode==='piece'?'selected':''}>Piece</option><option value="both" ${mode==='both'?'selected':''}>Both</option></select></label><div class="cart-tmt-qty">${mode!=='piece'?`<label>Bundles<input type="number" min="0" value="${i.bundles||0}" onchange="setTmtQty(${n},'bundles',this.value)"></label>`:''}${mode!=='bundle'?`<label>Pieces<input type="number" min="0" value="${i.pieces||0}" onchange="setTmtQty(${n},'pieces',this.value)"></label>`:''}<button class="remove-inline" onclick="removeCart(${n})">Remove</button></div></div>`}else if(p.packs){controls=`<div class="cart-control-stack"><label>Pack size<select onchange="setPaintPack(${n},this.value)">${[1,4,10,20].map(v=>`<option value="${v}" ${+i.pack===v?'selected':''}>${v} Litre</option>`).join('')}</select></label><div class="qty"><button onclick="changeQty(${n},-1)">−</button><input class="qty-input" type="number" min="1" value="${i.qty||1}" onchange="setCartQty(${n},this.value)"><button onclick="changeQty(${n},1)">+</button><button onclick="removeCart(${n})">×</button></div></div>`}else{controls=`<div class="qty"><button onclick="changeQty(${n},-1)">−</button><input class="qty-input" type="number" min="1" value="${i.qty||1}" onchange="setCartQty(${n},this.value)"><button onclick="changeQty(${n},1)">+</button><button onclick="removeCart(${n})">×</button></div>`}return `<div class="cart-item"><div class="cart-thumb"><img src="${img(p)}" style="width:100%;height:100%;object-fit:contain"></div><div><h5>${p.name}</h5><small>${p.brand||''} · ${c.desc}</small>${controls}</div><strong>${money(c.subtotal)}</strong></div>`}).join('');const t=totals();document.getElementById('cartSummary').innerHTML=`<div class="sum-line"><span>Subtotal</span><span>${money(t.subtotal)}</span></div><div class="sum-line"><span>Delivery</span><span>${money(t.delivery)}</span></div><div class="sum-line total"><span>Total</span><span>${money(t.total)}</span></div>`;document.getElementById('cartWhatsApp').href=whatsappUrl();updateCartBar(t)}
function persistCart(){localStorage.setItem('omSaiCartV1',JSON.stringify(cart));updateCart()}
function setCartQty(n,value){const qty=Math.max(1,parseInt(value,10)||1);if(!cart[n])return;cart[n].qty=qty;persistCart()}
function setTmtMode(n,mode){const i=cart[n];if(!i)return;i.mode=mode;if(mode==='bundle'){i.bundles=Math.max(1,i.bundles||1);i.pieces=0}else if(mode==='piece'){i.pieces=Math.max(1,i.pieces||1);i.bundles=0}else{i.bundles=Math.max(1,i.bundles||1);i.pieces=Math.max(1,i.pieces||1)}persistCart()}
function setTmtQty(n,key,value){const i=cart[n];if(!i)return;i[key]=Math.max(0,parseInt(value,10)||0);if((i.bundles||0)===0&&(i.pieces||0)===0){cart.splice(n,1)}persistCart()}
function setPaintPack(n,value){const i=cart[n];if(!i)return;i.pack=+value||1;persistCart()}
function changeQty(n,d){const i=cart[n];if(!i)return;if(i.bundles!==undefined||i.pieces!==undefined){if(i.mode==='both'){i.bundles=Math.max(0,(i.bundles||0)+d)}else if(i.mode==='piece'){i.pieces=Math.max(0,(i.pieces||0)+d)}else{i.bundles=Math.max(0,(i.bundles||0)+d)}if((i.bundles||0)===0&&(i.pieces||0)===0)cart.splice(n,1)}else i.qty=Math.max(1,(i.qty||1)+d);persistCart()}
function removeCart(n){cart.splice(n,1);persistCart()}
function whatsappText(order=null){const source=order||{items:cart,totals:totals()};const items=source.items||[];const t=source.totals||totals();let lines=['Hello Om Sai International,','I would like to place this order:',''];items.forEach((i,index)=>{const p=data.products.find(x=>x.id===i.id);if(!p)return;const c=itemCalc(i);lines.push(`${index+1}. ${p.name}${p.brand?' — '+p.brand:''}`);lines.push(`   Quantity: ${c.desc}`);if(c.weight!=null)lines.push(`   Total weight: ${c.weight} kg`);if(i.pack)lines.push(`   Pack size: ${i.pack} Litre`);if(i.colour)lines.push(`   Colour code: ${i.colour}`);lines.push(`   Product total: ${money(c.subtotal)}`);lines.push('')});lines.push(`Subtotal: ${money(t.subtotal)}`);lines.push(`${source.fulfillment==='pickup'?'Pickup':'Delivery'}: ${money(t.delivery)}`);lines.push(`GRAND TOTAL: ${money(t.total)}`);if(order){lines.push('',`Order ID: ${order.id}`,`Customer: ${order.name}`,`Phone: ${order.phone}`,`${order.fulfillment==='pickup'?'Collection':'Address'}: ${order.fulfillment==='pickup'?'Pickup from Om Sai International — customer may send someone else to collect':order.address}`,`Fulfilment: ${order.fulfillment==='pickup'?'Pickup':'Delivery'}`,`Payment: ${order.payment==='esewa'?'eSewa — '+order.transaction:'Cash on Delivery'}`)}lines.push('','Please confirm availability.');return lines.join('\n')}
function whatsappUrl(order=null){return 'https://wa.me/'+WA.replace('+','')+'?text='+encodeURIComponent(whatsappText(order))}
function updateCartBar(t=totals()){const bar=document.getElementById('cartBar');if(!bar)return;if(!cart.length){bar.classList.remove('show');return}const count=cart.reduce((s,i)=>s+cartItemCount(i),0);document.getElementById('cartBarCount').textContent=`${count} item${count===1?'':'s'}`;document.getElementById('cartBarTotal').textContent=money(t.total);const thumbs=document.getElementById('cartBarThumbs');if(thumbs)thumbs.innerHTML=cart.slice(0,3).map(i=>{const p=data.products.find(x=>x.id===i.id);return p?`<span class="cart-bar-thumb"><img src="${img(p)}" alt=""></span>`:''}).join('');bar.classList.add('show')}
function showCartBar(){updateCartBar()}
function openCart(){document.getElementById('cartDrawer').classList.add('open');document.getElementById('backdrop').classList.add('show');document.getElementById('cartBar').classList.remove('show')}
function closeCart(){document.getElementById('cartDrawer').classList.remove('open');document.getElementById('backdrop').classList.remove('show');updateCartBar()}
function quickCheckout(){if(!cart.length)return toast('Your cart is empty');checkout()}
function closeModal(id){document.getElementById(id).classList.remove('show')}
function checkout(){if(!cart.length)return toast('Your cart is empty');selectedFulfillment='delivery';document.getElementById('checkoutSummary').innerHTML=`<div class="cart-summary"><div class="sum-line"><span>Items</span><span>${cart.length}</span></div><div class="sum-line"><span>Subtotal</span><span>${money(totals('delivery').subtotal)}</span></div><div class="sum-line"><span>Delivery</span><span id="checkoutDelivery">${money(totals('delivery').delivery)}</span></div><div class="sum-line total"><span>Grand total</span><span id="checkoutTotal">${money(totals('delivery').total)}</span></div></div>`;document.querySelectorAll('input[name=fulfillment]').forEach(r=>r.checked=r.value==='delivery');updateFulfillment();document.getElementById('checkoutModal').classList.add('show')}
function updateFulfillment(){const pickup=selectedFulfillment==='pickup';const t=totals(selectedFulfillment);const deliveryEl=document.getElementById('checkoutDelivery'),totalEl=document.getElementById('checkoutTotal');if(deliveryEl)deliveryEl.textContent=pickup?'₹0 — Pickup':money(t.delivery);if(totalEl)totalEl.textContent=money(t.total);const address=document.querySelector('#checkoutForm [name=address]');const addressLabel=address?.closest('label');if(address){address.required=!pickup;address.placeholder=pickup?'Optional for pickup':'Enter full delivery address';if(addressLabel)addressLabel.firstChild.textContent=pickup?'Address (optional)':'Address*'}const pickupInfo=document.getElementById('pickupInfo');if(pickupInfo)pickupInfo.classList.toggle('hidden',!pickup)}
function setFulfillment(mode){selectedFulfillment=mode;updateFulfillment()}
function handleCheckout(e){e.preventDefault();const fd=new FormData(e.target),payment=fd.get('payment'),transaction=fd.get('transaction')||'',fulfillment=fd.get('fulfillment')||'delivery';selectedFulfillment=fulfillment;if(payment==='esewa'&&!transaction.trim())return toast('Enter transaction ID or phone number');const orderTotals=totals(fulfillment);const order={id:'OSI-'+Date.now().toString().slice(-7),date:new Date().toISOString(),name:fd.get('name'),phone:fd.get('phone'),address:fd.get('address')||'',fulfillment,fulfillmentLabel:fulfillment==='pickup'?'Pickup — customer/representative will collect':'Delivery',payment,transaction,items:cart.map(i=>({...i})),totals:orderTotals,status:'Order Placed'};const orders=JSON.parse(localStorage.getItem(ORDERS)||'[]');orders.unshift(order);localStorage.setItem(ORDERS,JSON.stringify(orders));const orderUrl=whatsappUrl(order);cart=[];localStorage.removeItem('omSaiCartV1');updateCart();closeModal('checkoutModal');showOrderSuccess(order,orderUrl);e.target.reset();selectedFulfillment='delivery';document.querySelector('input[name=payment][value=cod]').checked=true;document.querySelector('input[name=fulfillment][value=delivery]').checked=true;document.getElementById('esewaBox').classList.add('hidden')}
function renderAdmin(){const root=document.getElementById('adminRoot');if(localStorage.getItem(ADMIN)!=='ok'){root.innerHTML=`<div class="login-box"><span class="eyebrow">PRIVATE AREA</span><h3>Admin Portal</h3><p>This static version stores catalog data in this browser. A real secure multi-device admin system requires a backend later.</p><input id="adminPass" type="password" placeholder="Admin password"><button class="primary-btn full" onclick="adminLogin()">Enter Admin</button></div>`;return}root.innerHTML=`<div class="admin-top"><div><span class="eyebrow">CONTROL CENTER</span><h3>Om Sai Admin</h3></div><button class="ghost-btn" onclick="adminLogout()">Log out</button></div><div class="admin-tabs"><button class="admin-tab active" onclick="adminTab('products')">Products</button><button class="admin-tab" onclick="adminTab('delivery')">Delivery Rules</button><button class="admin-tab" onclick="adminTab('orders')">Orders</button><button class="admin-tab" onclick="adminTab('categories')">Categories</button></div><div id="adminContent"></div>`;adminTab('products')}
function adminLogin(){if(document.getElementById('adminPass').value==='admin123'){localStorage.setItem(ADMIN,'ok');renderAdmin()}else toast('Incorrect password')}
function adminLogout(){localStorage.removeItem(ADMIN);renderAdmin()}
function adminTab(tab){document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));[...document.querySelectorAll('.admin-tab')].find(x=>x.textContent.toLowerCase().startsWith(tab.slice(0,-1)))?.classList.add('active');const c=document.getElementById('adminContent');
if(tab==='products')c.innerHTML=`<div class="admin-help"><strong>Product Manager</strong><span>Add new products, change prices, assign categories, and upload product images.</span></div><div class="admin-list">${data.products.map(p=>`<div class="admin-product"><div style="display:flex;gap:10px;align-items:center"><img src="${img(p)}" style="width:46px;height:46px;border-radius:10px;object-fit:cover;background:#f3efff"><div><strong>${p.name}</strong><small>${p.category} · ${p.brand||'No brand'} · ${displayPrice(p)}</small></div></div><div class="admin-product-actions"><button class="mini-btn" onclick="editProduct('${p.id}')">Edit</button><button class="mini-btn danger" onclick="deleteProduct('${p.id}')">Delete</button></div></div>`).join('')}</div><button class="primary-btn full" onclick="showProductForm()">＋ Add New Product</button>`;
if(tab==='delivery')c.innerHTML=`<div class="admin-grid"><div class="admin-item"><h4>Cement delivery</h4><div class="admin-row"><label>Threshold bags<input id="d1" type="number" value="${data.delivery.cementThreshold}"></label><label>Charge/bag<input id="d2" type="number" value="${data.delivery.cementCharge}"></label></div></div><div class="admin-item"><h4>TMT delivery</h4><div class="admin-row"><label>Threshold bundles<input id="d3" type="number" value="${data.delivery.tmtBundleThreshold}"></label><label>Charge/bundle<input id="d4" type="number" value="${data.delivery.tmtCharge}"></label></div></div><div class="admin-item"><h4>Other categories</h4><div class="admin-row"><label>Minimum bill<input id="d5" type="number" value="${data.delivery.otherBillThreshold}"></label><label>Delivery charge<input id="d6" type="number" value="${data.delivery.otherCharge}"></label></div></div></div><button class="primary-btn full" onclick="saveDelivery()">Save delivery rules</button>`;
if(tab==='orders')renderOrdersAdmin(c);
if(tab==='categories')c.innerHTML=`<div class="admin-help"><strong>Category Manager</strong><span>Create completely new categories and upload a category image. Products can then be added to that category.</span></div><button class="primary-btn full" onclick="showCategoryForm()">＋ Add New Category</button><div class="admin-list" style="margin-top:12px">${data.categories.map((x,i)=>`<div class="admin-product"><div style="display:flex;gap:10px;align-items:center"><img src="${categoryImg(x)}" style="width:46px;height:46px;border-radius:10px;object-fit:cover;background:#f3efff"><div><strong>${x}</strong><small>${data.products.filter(p=>p.category===x).length} products</small></div></div><div class="admin-product-actions"><button class="mini-btn" onclick="editCategory(${i})">Edit</button><button class="mini-btn danger" onclick="deleteCategory(${i})">Delete</button></div></div>`).join('')}</div>`}
function renderOrdersAdmin(c){const orders=JSON.parse(localStorage.getItem(ORDERS)||'[]');c.innerHTML=`<div class="admin-help"><strong>Customer Orders</strong><span>${orders.length} order${orders.length===1?'':'s'} saved in this browser.</span><button class="save-btn" onclick="renderOrdersAdmin(document.getElementById('adminContent'))">↻ Refresh</button></div>${orders.length?`<div class="admin-list">${orders.map((o,idx)=>`<div class="order-card"><header><strong>${o.id}</strong><span class="status">${o.status||'Order Placed'}</span></header><p><b>${o.name}</b> · ${o.phone}<br>Fulfilment: <b>${o.fulfillment==='pickup'?'Pickup — customer/representative will collect':'Delivery'}</b><br>${o.fulfillment==='pickup'?'Collection: Om Sai International, Radhemai, Birgunj':'Address: '+(o.address||'—')}<br>Payment: ${o.payment==='esewa'?'eSewa — '+o.transaction:'Cash on Delivery'}<br>Subtotal: ${money(o.totals?.subtotal)} · ${o.fulfillment==='pickup'?'Pickup':'Delivery'}: ${money(o.totals?.delivery)}<br>Grand total: <b>${money(o.totals?.total)}</b></p><div class="order-items">${(o.items||[]).map(i=>{const p=data.products.find(x=>x.id===i.id);const cc=itemCalc(i);return `<div><b>${p?.name||i.id}</b><span>${cc.desc} — ${money(cc.subtotal)}</span></div>`}).join('')}</div><div class="order-actions"><button class="mini-btn" onclick="updateOrder(${idx},'Confirmed')">Confirm</button><button class="mini-btn" onclick="updateOrder(${idx},'On the Way')">On the Way</button><button class="mini-btn" onclick="updateOrder(${idx},'Delivered')">Delivered</button><button class="mini-btn" onclick="updateOrder(${idx},'Cancelled')">Cancel</button><button class="mini-btn danger" onclick="deleteOrder(${idx})">Delete</button></div></div>`).join('')}</div>`:'<div class="empty">No customer orders found in this browser yet.</div>'}`}
function saveDelivery(){data.delivery={cementThreshold:+d1.value,cementCharge:+d2.value,tmtBundleThreshold:+d3.value,tmtCharge:+d4.value,otherBillThreshold:+d5.value,otherCharge:+d6.value};saveData();toast('Delivery rules saved')}
function showCategoryForm(editIndex=null){const c=editIndex===null?null:data.categories[editIndex];const box=document.getElementById('adminContent');box.innerHTML=`<div class="admin-form"><div class="admin-help"><strong>${c?'Edit Category':'Add New Category'}</strong><span>${c?'Change the category name or image.':'Create a new category from scratch.'}</span></div><label>Category name<input id="catName" value="${c||''}" placeholder="e.g. Electrical"></label><label>Category image<input id="catImage" type="file" accept="image/*"><small>JPG, PNG or WebP · max 2MB</small></label>${c?`<img class="upload-preview" id="catPreview" src="${categoryImg(c)}">`:''}<div class="form-actions"><button class="ghost-btn" onclick="adminTab('categories')">Cancel</button><button class="primary-btn" onclick="saveCategoryForm(${editIndex===null?'null':editIndex})">Save Category</button></div></div>`;document.getElementById('catImage').onchange=e=>{readImage(e.target.files[0],src=>{if(src){let im=document.getElementById('catPreview');if(!im){im=document.createElement('img');im.id='catPreview';im.className='upload-preview';e.target.parentElement.appendChild(im)}im.src=src}})} }
function saveCategoryForm(i){const name=document.getElementById('catName').value.trim();if(!name)return toast('Enter a category name');if(i!==null&&data.categories.some((x,idx)=>idx!==i&&x.toLowerCase()===name.toLowerCase()))return toast('Category already exists');if(i===null&&data.categories.some(x=>x.toLowerCase()===name.toLowerCase()))return toast('Category already exists');const old=i===null?null:data.categories[i];if(i===null)data.categories.push(name);else data.categories[i]=name;const file=document.getElementById('catImage').files[0];const finish=src=>{if(old&&old!==name&&data.categoryImages?.[old]){data.categoryImages[name]=data.categoryImages[old];delete data.categoryImages[old]}if(src)data.categoryImages[name]=src;saveData();toast(i===null?'Category added':'Category updated');adminTab('categories')};if(file)readImage(file,finish);else finish('')}
function editCategory(i){showCategoryForm(i)}
function showProductForm(editId=null){const p=editId?data.products.find(x=>x.id===editId):null;const type=p?.packs?'paint':p?.category==='TMT'?'tmt':p?.variants?'variant':'standard';const c=document.getElementById('adminContent');c.innerHTML=`<div class="admin-form"><div class="admin-help"><strong>${p?'Edit Product':'Add New Product'}</strong><span>Fill the fields below. Upload a product image directly from your device.</span></div><div class="admin-row"><label>Product name<input id="pfName" value="${p?.name||''}" placeholder="Product name"></label><label>Brand<input id="pfBrand" value="${p?.brand||''}" placeholder="Brand"></label></div><div class="admin-row"><label>Category<select id="pfCategory">${data.categories.map(x=>`<option ${x===(p?.category||data.categories[0])?'selected':''}>${x}</option>`).join('')}</select></label><label>Product type<select id="pfType"><option value="standard" ${type==='standard'?'selected':''}>Standard (price × quantity)</option><option value="tmt" ${type==='tmt'?'selected':''}>TMT (kg/piece + kg/bundle)</option><option value="paint" ${type==='paint'?'selected':''}>Paint (1L / 4L / 10L / 20L)</option><option value="variant" ${type==='variant'?'selected':''}>Variants (different prices)</option></select></label></div><div id="pfExtra"></div><label>Product image<input id="pfImage" type="file" accept="image/*"><small>JPG, PNG or WebP · max 2MB. Leave empty to keep current image.</small></label>${p?`<img class="upload-preview" id="pfPreview" src="${img(p)}">`:''}<div class="form-actions"><button class="ghost-btn" onclick="adminTab('products')">Cancel</button><button class="primary-btn" onclick="saveProductForm('${editId||''}')">${p?'Save Changes':'Add Product'}</button></div></div>`;document.getElementById('pfType').onchange=()=>renderProductExtra(document.getElementById('pfType').value,p);renderProductExtra(type,p);document.getElementById('pfImage').onchange=e=>{readImage(e.target.files[0],src=>{if(src){let im=document.getElementById('pfPreview');if(!im){im=document.createElement('img');im.id='pfPreview';im.className='upload-preview';e.target.parentElement.appendChild(im)}im.src=src}})}}
function renderProductExtra(type,p){const e=document.getElementById('pfExtra');if(type==='tmt')e.innerHTML=`<div class="admin-row"><label>Price per kg<input id="pfPrice" type="number" value="${p?.price??0}"></label><label>Kg per piece<input id="pfPiece" type="number" step="0.01" value="${p?.kgPiece??0}"></label><label>Kg per bundle<input id="pfBundle" type="number" step="0.01" value="${p?.kgBundle??0}"></label></div><label>Unit<input id="pfUnit" value="Kg"></label>`;else if(type==='paint')e.innerHTML=`<div class="admin-row"><label>1 L price<input id="pk1" type="number" value="${p?.packs?.[1]??0}"></label><label>4 L price<input id="pk4" type="number" value="${p?.packs?.[4]??0}"></label></div><div class="admin-row"><label>10 L price<input id="pk10" type="number" value="${p?.packs?.[10]??0}"></label><label>20 L price<input id="pk20" type="number" value="${p?.packs?.[20]??0}"></label></div><label>Unit<input id="pfUnit" value="Litre"></label>`;else if(type==='variant')e.innerHTML=`<label>Variants and prices <small>One per line, format: size = price</small><textarea id="pfVariants" rows="4" placeholder="2.5 inch = 200\n4 inch = 250">${p?.variants?Object.entries(p.variants).map(([k,v])=>`${k} = ${v}`).join('\n'):''}</textarea><label>Unit<input id="pfUnit" value="${p?.unit||'Piece'}"></label>`;else e.innerHTML=`<div class="admin-row"><label>Price<input id="pfPrice" type="number" value="${p?.price??0}"></label><label>Unit<select id="pfUnit"><option ${p?.unit==='Bag'?'selected':''}>Bag</option><option ${p?.unit==='Kg'?'selected':''}>Kg</option><option ${p?.unit==='Piece'?'selected':''}>Piece</option><option ${p?.unit==='Litre'?'selected':''}>Litre</option></select></label></div>`}
function saveProductForm(editId){const name=document.getElementById('pfName').value.trim();if(!name)return toast('Enter a product name');const category=document.getElementById('pfCategory').value,brand=document.getElementById('pfBrand').value.trim(),type=document.getElementById('pfType').value;let p=editId?data.products.find(x=>x.id===editId):{id:'p-'+Date.now(),image:'others.svg'};p.name=name;p.category=category;p.brand=brand;if(type==='tmt'){p.unit='Kg';p.price=+document.getElementById('pfPrice').value||0;p.kgPiece=+document.getElementById('pfPiece').value||0;p.kgBundle=+document.getElementById('pfBundle').value||0;delete p.packs;delete p.variants}else if(type==='paint'){p.unit='Litre';p.packs={1:+document.getElementById('pk1').value||0,4:+document.getElementById('pk4').value||0,10:+document.getElementById('pk10').value||0,20:+document.getElementById('pk20').value||0};delete p.price;delete p.variants}else if(type==='variant'){p.unit=document.getElementById('pfUnit').value;p.variants={};document.getElementById('pfVariants').value.split('\n').forEach(line=>{const [k,v]=line.split('=');if(k&&v)p.variants[k.trim()]=+v.trim()||0});delete p.price;delete p.packs}else{p.unit=document.getElementById('pfUnit').value;p.price=+document.getElementById('pfPrice').value||0;delete p.packs;delete p.variants;delete p.kgPiece;delete p.kgBundle}const file=document.getElementById('pfImage').files[0];const finish=src=>{if(src)p.imageData=src;if(!editId)data.products.unshift(p);saveData();toast(editId?'Product updated':'Product added');adminTab('products')};if(file)readImage(file,finish);else finish('')}
function editProduct(id){showProductForm(id)}
function deleteProduct(id){if(confirm('Delete this product?')){data.products=data.products.filter(p=>p.id!==id);saveData();toast('Product deleted');adminTab('products')}}
function newProduct(){showProductForm()}
function addCategory(){showCategoryForm()}
function deleteCategory(i){const c=data.categories[i];if(data.products.some(p=>p.category===c))return toast('Delete or move its products first');if(confirm(`Delete category "${c}"?`)){data.categories.splice(i,1);delete data.categoryImages?.[c];saveData();toast('Category deleted');adminTab('categories')}}
function updateOrder(i,status){const o=JSON.parse(localStorage.getItem(ORDERS)||'[]');o[i].status=status;localStorage.setItem(ORDERS,JSON.stringify(o));renderOrdersAdmin(document.getElementById('adminContent'));toast('Order status updated')}
function deleteOrder(i){const o=JSON.parse(localStorage.getItem(ORDERS)||'[]');o.splice(i,1);localStorage.setItem(ORDERS,JSON.stringify(o));renderOrdersAdmin(document.getElementById('adminContent'));toast('Order deleted')}
window.addEventListener('storage',e=>{if(e.key===ORDERS&&localStorage.getItem(ADMIN)==='ok'&&document.getElementById('adminModal')?.classList.contains('show')&&document.getElementById('adminContent')?.querySelector('.order-card'))renderOrdersAdmin(document.getElementById('adminContent'))});
document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;document.getElementById('backdrop').onclick=closeCart;document.getElementById('cartBar').onclick=e=>{e.preventDefault();openCart()};document.getElementById('checkoutBtn').onclick=checkout;document.getElementById('moreProductsBtn').onclick=showMoreProducts;document.getElementById('checkoutForm').addEventListener('submit',handleCheckout);document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('a[data-nav]').forEach(a=>a.addEventListener('click',e=>{if(a.dataset.nav==='admin'){e.preventDefault();openAdmin()}document.getElementById('mobileMenu').classList.remove('show')}));const menuBtn=document.getElementById('menuBtn'),mobileMenu=document.getElementById('mobileMenu');menuBtn.onclick=e=>{e.stopPropagation();mobileMenu.classList.toggle('show')};mobileMenu.onclick=e=>e.stopPropagation();document.addEventListener('click',e=>{if(!mobileMenu.contains(e.target)&&e.target!==menuBtn)mobileMenu.classList.remove('show')});document.getElementById('allProductsBtn').onclick=()=>{activeCategory='All';visibleProductCount=12;renderAll();document.getElementById('product-list').scrollIntoView({behavior:'smooth',block:'start'})};document.querySelectorAll('input[name=payment]').forEach(r=>r.addEventListener('change',()=>document.getElementById('esewaBox').classList.toggle('hidden',r.value!=='esewa'||!r.checked)));document.querySelectorAll('input[name=fulfillment]').forEach(r=>r.addEventListener('change',()=>setFulfillment(r.value)));document.getElementById('year').textContent=new Date().getFullYear();setTimeout(()=>{document.getElementById('intro').classList.add('done');document.body.style.overflow='auto'},2500);if(location.hash==='#admin')openAdmin();document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='a'){e.preventDefault();openAdmin()}});renderAll();
